In [1]:
!pip install numpy --upgrade

1. Import the numpy package under the name np

In [2]:
import numpy as np
import math

2. Print the numpy version and the configuration (★☆☆)

In [10]:
print(np.__version__)


2.2.3


3. Create a null vector of size 10 (★☆☆)

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [12]:
np.zeros(10).shape

(10,)

5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
arr1 = np.zeros(10);
arr1[4] = 1;
print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
arr2 = np.arange(10,50)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [26]:
np.flip(arr2)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [36]:
arr = [1,2,0,0,4,0]
for index,i in enumerate(arr):
    if(i != 0):
        print("Non-zero element :" ,index)
    i += 1

Non-zero element : 0
Non-zero element : 1
Non-zero element : 4


In [38]:
## Another method
np.nonzero(arr)

(array([0, 1, 4]),)

11. Create a 3x3 identity matrix (★☆☆)

In [40]:
arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [42]:
arr4 = np.random.rand(27).reshape(3,3,3)
print(arr4)

[[[0.81513944 0.59889927 0.8190973 ]
  [0.91058771 0.83331536 0.98365142]
  [0.01769431 0.99984276 0.04154518]]

 [[0.23569484 0.73541394 0.6553823 ]
  [0.54514908 0.766754   0.52386723]
  [0.26265812 0.34991973 0.75082292]]

 [[0.68975533 0.0868439  0.43266231]
  [0.98811629 0.18230663 0.73620283]
  [0.07874734 0.31234762 0.85341584]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [23]:
arr5 = np.random.randint(0,101,size=100).reshape(10,10)
print(arr5)
print("The maximum is :",np.max(arr5))
print("The maximum is :",np.min(arr5))

[[ 1 53 19 65 16 59 98 31 29 66]
 [55 82 25  8 66 11 66 91 30 94]
 [10 65 22 91 30 61 49 23 39 99]
 [58 94 96 50 71 91 82 36 16 76]
 [77 18 55 39 55 80  2 62 72 64]
 [60 25 64 81 86 94 39 30 73 82]
 [46  6 42 92 20  4 12 56  9  7]
 [93 34 62 58 17 15 17 12 31 79]
 [95 35 86 60 78 59 91 45 44 98]
 [90 45 22 87  1 70 16 26 14 31]]
The maximum is : 99
The maximum is : 1


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [30]:
arr6 = np.random.randint(0,1000,size=30)
print(arr6)
print(arr6.mean())

[311  74 708 942 954 538 882 475 525 481 279 465 260 185 162 881 191 829
 347 518 784 976 668 755  71 165  93 139 685 876]
507.3


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
arr7 = np.zeros(25).reshape(5,5)
arr7[0,:] = arr7[:, 0] = arr7[-1,:] = arr7[:,-1] = 1
print(arr7)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
### Another way
arr8 = np.zeros(25).reshape(5,5)
arr8_padded = np.pad(arr8 , pad_width= 2, mode='constant',constant_values = 1)
print(arr8_padded)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [21]:
arr8 = np.ones(25).reshape(5,5)
arr8_padded = np.pad(arr8 , pad_width= 2, mode='constant',constant_values = 0)
print(arr8_padded)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

`0 * np.nan = np.nan` .Not a number

`np.nan + np.nan` . Any arithmetic operation with nan , will return nan .

`np.nan == np.nan` . Beacuse not a number is nothing how can be they equal

`np.inf > np.nan` . Not a number is not known , so it cannot be equal , larger or 

`np.nan in set([np.nan])` this will return true as the set onctains only one element which is not a number .

`0.3 == 3 * 0.1` This will return as false no matter what

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [5]:
diag_elements = np.array([1,2,3,4,5])
diagonal_matrix = np.diag(diag_elements)
print(diagonal_matrix)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [10]:
arr8 = np.zeros((8, 8), dtype=int)
arr8[::2,1::2] = 1
arr8[1::2, ::2] = 1
arr8

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
    
    Ans : `arr9[5,6,7]`

In [13]:
arr9 = np.random.randint(0,1000,size=(6,7,8))
print(arr9)
arr9[5,6,7]

[[[368 385 954 611 284 576 376 879]
  [ 16 255 903 861 953 630 720 993]
  [720 711 630 945 538 907  15 339]
  [654 812 576 589 785 214  48 587]
  [ 21 380  21 297 442 115  79 951]
  [886 245  38 677 224 594 606 426]
  [387 600 384 293 250 596 408 757]]

 [[181 166 986 510 372 464 604 422]
  [646 254 626 448 895 738 502 742]
  [185 913 680 531 255 731 801 592]
  [150 767 184 368 274 923 562 287]
  [910 363 668  48 670 370 657 965]
  [155 450 520 104 484 769 567 789]
  [712 620 856 409 425 147  17 751]]

 [[657 710 163 656 123 819 358 581]
  [ 19 697 799 234 352 291 645 677]
  [765 576 693 287 301 284 495 332]
  [329 594  84 306 903 799 245 843]
  [714 928 185 373 181 572 994 317]
  [ 13 456 426 180 473 579 284 635]
  [692 309 169 738 910 740 502 496]]

 [[407 827 902 736 568 680 966  84]
  [648 133 727 290 139 168 300 333]
  [908 959 437 217 930 696 291 359]
  [192 699  39 968 757 250 701 205]
  [133  91 777  69 934 220 251  18]
  [792 204 519 214 623 523 190 996]
  [699 916  55 524 872

np.int32(47)